---
- name: Market csgo parser service
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    weapon_types:
      - AK-47

    market_types:
      - dmarket
      - cs-money
      - haloskins
      - market-csgo
      - skinport
      - bitskins
      - skinbid
      - csfloat

  tasks:
    - name: Set arm_arch based on architecture
      set_fact:
        arm_arch: "{{ ansible_architecture == 'arm64' }}"
    - name: Create Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: ./docker-compose.yml
    - name: Run docker-compose
      command: docker-compose up -d --build --force-recreate
      args:
        chdir: .