version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080:5432"
    networks:
      - parser_network

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_JETTY_MAX_THREAD_POOL_SIZE: 10
      MB_JVM_MAX_HEAP_SIZE: 512m
    ports:
      - "3000:3000"
    networks:
      - parser_network

  items:
    build: 
      context: .
      dockerfile: ./items_parser/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "parser.py"]
    networks:
      - parser_network

networks:
  parser_network:
    driver: bridge
