version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080:5432"
    networks:
      - parser_network

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GF_AUTH_DISABLE_INITIAL_SETUP=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    volumes:
      - ./grafana/dashboards/home.json:/etc/grafana/provisioning/dashboards/home.json
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
    networks:
      - parser_network
    depends_on:
      - db

  items:
    build: 
      context: .
      dockerfile: ./items_parser/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "parser.py"]
    networks:
      - parser_network

networks:
  parser_network:
    driver: bridge
