apiVersion: 1

datasources:
  - name: PostgresDB
    type: postgres
    access: proxy
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: db
    jsonData:
      sslmode: disable
      timescaledb: false
      postgresVersion: 120
      timeColumn: time
      timeColumnType: timestamp
      tableColumn: table
      metricColumn: metric
      jsonQuery: true
      sqlQuery: |
        SELECT name, quality, is_stattrak, link, skins.price
        FROM skins
        INNER JOIN weapons_prices ON weapons_prices.id = skins.skin_id
      authType: anonymous
      defaultRole: Viewer
    editable: true
    readOnly: true
    meta:
      query: skins
      defaultDatasource: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}