name: Build
on: push

env:
  ANSIBLE_VAULT_PASSWORD_FILE: ~/.vault_pass.txt
  ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ["worker", "dashboard", "infrastructure"]

    name: Build, test and publish app Docker images (${{ matrix.build_type }})
    steps:
      - uses: actions/checkout@v3

      - name: Drop ansible vault password to file
        run: echo "${{ env.ANSIBLE_VAULT_PASSWORD }}" > ${{ env.ANSIBLE_VAULT_PASSWORD_FILE }}

      - name: Prepare build configuration for ${{ matrix.build_type }}
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          ansible-playbook prepare-build-config.yml

      - name: Build the docker-compose stack
        run: docker network create parser_network && docker-compose up --build --no-start

      - name: Get init logs
        run: docker-compose logs

      - name: Publish image(s)
        run: |
          docker tag ${{ matrix.build_type }}_build ${{ secrets.DOCKER_USERNAME }}/${{ matrix.build_type }}:${{ github.sha }} && \
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.build_type }}:${{ github.sha }}
